### ISSUE TITLE
Проблема с запуском на новом инстансе

### ISSUE THREAD

**Issue by baddboy40** [oknosoft/metadata-auth-proxy#5]
Есть проблема с запуском на новом инстансе.
Отсутствуют необходимые библиотеки в сборке и используется устаревший метод подключения и генерации Material UI.

**Comment by unpete** [comment]
Material UI вообще не используется в серверной части. Сборка proxy так же - не требуется. Это просто файлы, которые стартуют в node.

Отделить редактор цветов и метаданных от собственно proxy было бы полезно. Это все осознали несколько лет назад, но эту работу не впихнуть в один или 10 коммитов. Там над концепцией думать надо.

**Comment by unpete** [comment]
> Есть проблема с запуском

Какая именно проблема? Почему на двух десятках моих экземпляров не проявляется?

**Comment by baddboy-obn** [comment]
при npm run start вылетает ошибка о недостающих в package.json зависимостях, почему в других не выскакивает: скорее всего из-за того что эти зависимости устанавливались в ручном режиме уже после забора из гита основной ветки.

**Comment by baddboy-obn** [comment]
> > Есть проблема с запуском
> 
> Какая именно проблема? Почему на двух десятках моих экземпляров не проявляется?

Потому что доустанавливали в ручном режиме не достающие библиотеки, или же они были установлены глобально!

**Comment by unpete** [comment]
Гипотеза интересная, но нет.
proxy я устанавливаю и обновляю на чистых контейнерах двумя строками: git fetch и yarn install

**Comment by baddboy-obn** [comment]
> Гипотеза интересная, но нет.
> proxy я устанавливаю и обновляю на чистых контейнерах двумя строками: git fetch и yarn install

в package json отсутствуют зависимости и на этапе yarn install процесс валится

**Comment by unpete** [comment]
> на этапе yarn install процесс валится

@baddboy-obn вы, наверное, аудиторию перепутали. Здесь взрослые люди, которые понимают, что если в json нет синтаксических ошибок, то `yarn install` никак не может отвалиться.
