### ISSUE TITLE
Преимущество .latin в http/proxy-couchdb при генерации proxy_auth хедеров

### ISSUE THREAD

**Issue by ermouth** [oknosoft/metadata-auth-proxy#9]
https://github.com/oknosoft/metadata-auth-proxy/blob/901a0e5bd2e68a42686b72e23992ad05960728ab/server/http/proxy-couchdb.js#L63

Преимущество `.latin` – второстепенного вроде поля – создаёт чрезвычайно трудноуловимую ошибку, если взведён server.single_db. Если юзернейм дублёра в CouchDB и значение поле `.latin` не совпадают, авторизоваться не получится.

Пример такого юзера – Fenster на Квикокнах.

**Comment by unpete** [comment]
> второстепенного вроде поля

Оно скорее, служебное, чем второстепенное. Человек это поле не правит никогда. Поле заполняется методом `Транслит()` библиотеки интеграции в событии `ПередЗаписью`

В подсистемах `Авторизация` и `Пользователи`, запланированы масштабные изменения - другие метаданные и другой уровень совместимости с типовыми 1С. Дорабатывать сегодняшнюю реализацию этих подсистем смысла не вижу (за исключением критических ошибок)
